In [1]:
import numpy as np 

In [2]:
arr1 = np.arange(10)
print(arr1.shape)

(10,)


In [3]:
arr2 = np.arange(1,10).reshape(3, 3)
print(arr2.shape)

(3, 3)


In [4]:
zeros = np.zeros((2, 4))
unos = np.ones((4, 3))
sietes = np.full((2, 2), 7)

In [5]:
aleatorios = np.random.random((2, 2))

In [8]:
arr = np.array([[1, 2, 3], [3, 4, 5]])
print("Tamaño:", arr.size)
print("Dimensiones:", arr.ndim)

Tamaño: 6
Dimensiones: 2


In [ ]:
# Indexación básica
arr = np.array([10, 20, 30, 40])
print("Primero:", arr[0])
print("Último:", arr[-1])

Primero: 10
Último: 40
Del 20 al 40: [20 30 40]


In [ ]:
# Slicing
print("Del 20 al 40:", arr[1:10])
a = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
b = a[ : 2, 1 : 3]
print(a[0, 1]) # == 2

# b es un puntero, por lo que también se cambia la matriz a
b[0, 0] = 78
print(a[0, 1]) # == 78

Del 20 al 40: [20 30 40]
2
78


In [21]:
# Indexado booleano
arr = np.array([5,12,8,3,15,1,9])
mayores_7 = arr[arr > 7]

bool_idx = arr > 7
print(bool_idx)
print(arr[bool_idx])

[False  True  True False  True False  True]
[12  8 15  9]


In [ ]:
# element-wise operations
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Suma:", a + b)
print("Resta:", a - b)
print("Multiplicación:", a * b) 
print("División:", a / b)

Suma: [5 7 9]
Resta: [-3 -3 -3]
Multiplicación: [ 4 10 18]
División: [0.25 0.4  0.5 ]


In [31]:
# Operaciones de matrices
x = np.array([[1,2], [3, 4]])
y = np.array([[1,2], [3, 4]])
print("Producto matricial:\n", x.dot(y))

Producto matricial:
 [[ 7 10]
 [15 22]]


In [ ]:
v = np.array([2,5,3,5,7])
print(np.dot(x, v))

ValueError: shapes (2,2) and (5,) not aligned: 2 (dim 1) != 5 (dim 0)

In [32]:
# operaciones estadísticas
arr = np.array([2,5,8,3,9,1,7,4])
print("Media:", np.mean(arr))
print("Mediana:", np.median(arr))
print("Desviación:", np.std(arr))

Media: 4.875
Mediana: 4.5
Desviación: 2.7128168017763383


In [37]:
# operación flatten
arr = np.arange(12)
arr_3x4 = arr.reshape(3, 4)
arr_6x2 = arr.reshape(6, 2)
arr_1d = arr_6x2.flatten()

In [40]:
# NANs
arr = np.array([1, 2, np.nan, 4, np.nan, 6])
sin_nan = np.nan_to_num(arr, nan=0)

In [44]:
# Where
arr = np.array([1,-2,3,-4,5,-6])
print("arr", arr)

arr_positivo = np.where(arr < 0, 0, arr)

# Ejemplo de aplicación real
#   Sustituir los valores nulos por la media
sin_nan_media = np.where(np.isnan(arr), np.nanmean(arr), arr)
print(sin_nan_media)

arr [ 1 -2  3 -4  5 -6]
[ 1. -2.  3. -4.  5. -6.]


In [48]:
# Concatenación vertical
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])

vertical = np.concatenate([a,b], axis=0)
print("a =", a)
print("b =", b)
print("vertical =", vertical)

a = [[1 2]
 [3 4]]
b = [[5 6]]
vertical = [[1 2]
 [3 4]
 [5 6]]


In [49]:
# sort
arr = np.array([34,12,78,3,5,7])
print("Ascendente:", np.sort(arr))
print("Descendente:", np.sort(arr)[::-1])

Ascendente: [ 3  5  7 12 34 78]
Descendente: [78 34 12  7  5  3]
